### ISSUE TITLE
Missing error handling if email/handle doesn't match regexpression

### ISSUE THREAD

**Issue by m-overlund** [RadarsofthouseDev/reepay-payment-for-magento1#2] opened 2019-10-14 07:59 UTC
**Scenario:**
Customer buys some products, goes to checkout, uses for instance "+" character in the email address, or other special character that is allowed in Magento field validation, and goes to checkout.

**Expected result:**
Payment window opens up and customer can pay or gets error message.

**Actual result:**
Payment window opens blank, only with logo and nothing else. The page "breaks".

**Log result:**
DEBUG (7): onCheckoutSubmitAllAfter
DEBUG (7): Cannot create Reepay payment session
DEBUG (7): onCheckoutSubmitAllAfter() exception: Cannot create Reepay payment session

**Comment by RadarsofthouseDev** [comment] 2021-11-04 03:45
We apologize for the late reply. We have many updated from 2019.
We just tested the latest version (1.0.45) with the clean standard Magento 1 but we cannot reproduce the issue here.

test case : 
https://prnt.sc/1yaitk9
https://prnt.sc/1yail4d
https://prnt.sc/1yaive1

Maybe the issue was solved from Reepay API section. Allowed special character for the email.
However, we will close the issue for now. Please let us know if you still have the problem.

**Closed as completed by RadarsofthouseDev** 2021-11-04 03:45 UTC

**Comment by m-overlund** [comment] 2021-11-05 09:15
It does not work for us - latest Magento and Reepay - M1.9.4.5 + Reepay 1.0.45.
tried with michael+1@xxx.com again.
Redirect to gateway fails, no user is created in Reepay or anything.

![fyrselv-gateway](https://user-images.githubusercontent.com/504236/140487436-f41c672c-1273-4db3-9b90-3432e43a2b29.jpg)

**Comment by RadarsofthouseDev** [comment] 2021-11-08 08:54
@m-overlund

We found a bug about the customer handle.
We have fixed the issue and updated the module to V1.0.46.
Please update the module to the latest version.

**Comment by m-overlund** [comment] 2021-11-08 09:18
Confirmed the fix works - thanks.
